package Mahesh;

import java.util.Arrays;
import java.util.Objects;

// Heap memory area -> divided into Constant Pool Area and Non-Constant pool area

// Constant pool area -> Strings which are created by assigning the value to the string variable are stored in this area
// Non -constant pool area -> Strings which are generated by 'new' keywords are stored in this area.

// System.identityHashCode() --> method to find out the memory address where the variable is stored

// Arrays.toString(values);	// converts 'values' into array format --> [abc, 123, xyz]


public class String_study {
	
	public static void main(String[] args) {

		String s1 = "Mahesh";		// s1,s2,s3 are stored in constant pool area.
		String s2 = "Mahesh";	
		String s3 = "Mahesh";
		
        System.out.println(System.identityHashCode(s1)); 	// method to find out memory address - 1159190947
        System.out.println(System.identityHashCode(s2));	//1159190947
        System.out.println(System.identityHashCode(s3));	//1159190947

// the memory address of the s1,s2,s3 are same. That means only one object is created and stored in the memory/string constant pool area
        //and s1,s2,s3 are pointing to the same object.
// if we want to update the s1 then, only the reference will be updated and s1 will point to the new object
        //but s2 and s3 references are remains and will be pointing to the same object/memory location
       
        s1+=" More";
        System.out.println(s1);
        System.out.println("New memory address of s1: "+System.identityHashCode(s1)); 	// new memory address - 1159190947
      		
		System.out.println(s1+' '+s2);
		
		String s5 = new String("Hello");
		String s6 = new String("Hello");
		String s7 = new String("Hello");
		
        System.out.println(System.identityHashCode(s5));		// 1406718218
        System.out.println(System.identityHashCode(s6));		// 245257410
        System.out.println(System.identityHashCode(s7));		// 1705736037
        
// The memory address of the s5,s6,s7 objects are different even if the content "Hello" is same.
// i.e.different objects are created and stored in the different memory when we create a string with 'new' keyword.
		
        System.out.println("******************************");
        System.out.println("String Methods: ");
        System.out.println();
        
      // String Methods
        String str1 = "Hello World   ";
        String str2 = "world";
        String str3 = "Hello";
        String str4 = "HELLO";
        String str5 = new String("HELLO");
       		
        int l = str1.length();
		System.out.println("The length of "+str1+" including space is: "+l);
		System.out.println("Characher at 0th index in 'HELLO' is: "+str3.charAt(0));
		System.out.println("Is the contents of str4 and str5 is same? "+ str4.equals(str5));
		System.out.println("Is the memory address of str4 and str5 is same?  "+ (str4==str5));
		System.out.println("Are the str3 and str4 are same in case(Upper and lower case)? "+str4.equals(str3));
		System.out.println("Are the content of str3 and str4 same(in any Upper or Lower case)? "+ str3.equalsIgnoreCase(str4));
	
        System.out.println("******************************");
		
		int i = str2.compareTo(str1);		// finds out the difference between ascii value of two strings(compares char by char)
		System.out.println('w'+0);		//finds out the ascii value of 'w'
		System.out.println('H'+0);		//finds out the ascii value of 'H'
		System.out.println(i);
		
		System.out.println(str2.toUpperCase());		//converts string into Uppercase
		System.out.println(str4.toLowerCase());		// converts string into Lowercase
		
		String replaced=str1.replace("World", "Duniya");	// replace the part of the string or full string
		System.out.println("String after replacing World by Duniya: "+replaced);
		String rplc = str1.replace('l', 'p').toUpperCase();
		System.out.println("String after replacing l by p and all in uppercase: "+rplc);		
		
		String st="Java is platform independent language. Java is oops language.Java language has JDK,JVM,JRE and JIT compiler.";
		System.out.println(st);
		String st1 =st.replace("Java", "Bava");
		String st2 = st1.replace("language", "bbaanguage");
		System.out.println(st2);
		
System.out.println("******************************");
		
		str1=str1.trim();				// trims the spaces from begging and ending of the string
		System.out.println(str1);
		System.out.println(str1.length());
		
		System.out.println(str2.contains("rl"));		

		String x = "This world is full of smart as well as fool people.";
		
		System.out.println(x.toUpperCase());
		System.out.println(x.toLowerCase());
		
		System.out.println(x.substring(7));			// gives substring from given index to last
		System.out.println(x.substring(7, 20));		// gives substring from start index to end index 
		System.out.println(x.subSequence(7, 20));	// same as substring()
		
		System.out.println(x.startsWith("Thi"));		// true
		System.out.println(x.endsWith("ple."));			//true
		
		System.out.println(x.indexOf("i"));		// gives index of 1st occurrence of 'i'		
		System.out.println(x.lastIndexOf("i"));		// gives index of last occurrence of 'i'
		
 System.out.println("******************************");
	
		String a = "";
		String b = "  ";
		String ab = null;
		
		System.out.println(a.isEmpty());		//true
		System.out.println(a.isBlank());		//true
		System.out.println(b.isEmpty());		//false
		System.out.println(b.isBlank());		//true
		
		System.out.println(Objects.isNull(a));		//false
		System.out.println(Objects.isNull(b));		//false
		System.out.println(Objects.isNull(ab));		//true
	
System.out.println("*************************************");		
		
		String s = "Mahesh";
		System.out.println(s.getClass().getName());		// gives us class name with package
		System.out.println(s.getClass().getSimpleName()); // gives us only class name, without package -> String
		
		//these methods are only used with non-primitive data types like String,Integer etc.
		//for primitive data types like int,float,double,char,boolean etc. we need to convert it into Object class and then we will get the class name
		
		
		int c = 10;
		System.out.println(((Object)c).getClass().getSimpleName());		// Integer

		//valueOf() method coverts given type such as int, long, float, double, boolean, char into String.	
		
		String d = String.valueOf(c);		// converts 'int' value to 'String' value.
		System.out.println(d);
	
		System.out.println(d.getClass().getSimpleName()); // Now it is String

		System.out.println("*************************************");		

		
		//split ex1
		String y = "Java is intresting language.";
		String words[] = y.split(" ");
		
		for(String w:words) {
			System.out.println(w);
		}
	
		//split ex2
		String amount = "$1,59,38,20";
		String amount1 = amount.replace("$","");
		
		String	amt[]= amount1.split(",");		
		for(String m:amt)
		{
			System.out.println(m);
		}
		
		
		//split ex3
		s ="abc,123@xyz";
		String values1[]=s.split(",");
		System.out.println(Arrays.toString(values1));	// converts values1 into array format --> [abc, 123@xyz]
		
		String values2[] = values1[1].split("@");
		System.out.println(Arrays.toString(values2));		// [123, xyz]
		
		System.out.println(values1[0]);
		System.out.println(values2[0]);
		System.out.println(values2[1]);
		
		
		
		//concat()
		String xy = "Mahesh";
		String xz = "More";
		String output = xy.concat(" ").concat(xz);
		System.out.println("My name after concatenation is : "+output);
		
		System.out.println("Hello".concat(" Word!").concat(" Welcome to").concat(" Java."));
		
	}

}
